version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive
    - staticcheck
    - thelper
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - errcheck
        path: testutil\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - workspaces/
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/obot-platform/discobot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - workspaces/
